export interface MitreTechnique {
  id: string;
  name: string;
  subtechniques?: { id: string; name: string }[];
}

export interface MitreTactic {
  id: string;
  name: string;
  shortName: string;
  description: string;
  techniques: MitreTechnique[];
}

export const MITRE_TACTICS: MitreTactic[] = [
  {
    id: "TA0043",
    name: "Reconnaissance",
    shortName: "reconnaissance",
    description: "Gathering information to plan future adversary operations.",
    techniques: [
      { id: "T1595", name: "Active Scanning", subtechniques: [{ id: "T1595.001", name: "Scanning IP Blocks" }, { id: "T1595.002", name: "Vulnerability Scanning" }] },
      { id: "T1592", name: "Gather Victim Host Information" },
      { id: "T1589", name: "Gather Victim Identity Information" },
      { id: "T1590", name: "Gather Victim Network Information" },
      { id: "T1591", name: "Gather Victim Org Information" },
      { id: "T1598", name: "Phishing for Information" },
      { id: "T1597", name: "Search Closed Sources" },
    ],
  },
  {
    id: "TA0042",
    name: "Resource Development",
    shortName: "resource-development",
    description: "Establishing resources to support operations.",
    techniques: [
      { id: "T1583", name: "Acquire Infrastructure" },
      { id: "T1586", name: "Compromise Accounts" },
      { id: "T1584", name: "Compromise Infrastructure" },
      { id: "T1587", name: "Develop Capabilities" },
      { id: "T1585", name: "Establish Accounts" },
      { id: "T1588", name: "Obtain Capabilities" },
    ],
  },
  {
    id: "TA0001",
    name: "Initial Access",
    shortName: "initial-access",
    description: "Techniques used to gain an initial foothold within a network.",
    techniques: [
      { id: "T1189", name: "Drive-by Compromise" },
      { id: "T1190", name: "Exploit Public-Facing Application" },
      { id: "T1133", name: "External Remote Services" },
      { id: "T1200", name: "Hardware Additions" },
      { id: "T1566", name: "Phishing", subtechniques: [{ id: "T1566.001", name: "Spearphishing Attachment" }, { id: "T1566.002", name: "Spearphishing Link" }] },
      { id: "T1091", name: "Replication Through Removable Media" },
      { id: "T1195", name: "Supply Chain Compromise" },
      { id: "T1199", name: "Trusted Relationship" },
      { id: "T1078", name: "Valid Accounts" },
    ],
  },
  {
    id: "TA0002",
    name: "Execution",
    shortName: "execution",
    description: "Techniques that result in adversary-controlled code running on a local or remote system.",
    techniques: [
      { id: "T1059", name: "Command and Scripting Interpreter", subtechniques: [{ id: "T1059.001", name: "PowerShell" }, { id: "T1059.003", name: "Windows Command Shell" }, { id: "T1059.004", name: "Unix Shell" }] },
      { id: "T1203", name: "Exploitation for Client Execution" },
      { id: "T1559", name: "Inter-Process Communication" },
      { id: "T1106", name: "Native API" },
      { id: "T1053", name: "Scheduled Task/Job", subtechniques: [{ id: "T1053.005", name: "Scheduled Task" }] },
      { id: "T1129", name: "Shared Modules" },
      { id: "T1204", name: "User Execution" },
      { id: "T1047", name: "Windows Management Instrumentation" },
    ],
  },
  {
    id: "TA0003",
    name: "Persistence",
    shortName: "persistence",
    description: "Techniques used to maintain access to systems across restarts and credential changes.",
    techniques: [
      { id: "T1098", name: "Account Manipulation" },
      { id: "T1197", name: "BITS Jobs" },
      { id: "T1547", name: "Boot or Logon Autostart Execution", subtechniques: [{ id: "T1547.001", name: "Registry Run Keys" }] },
      { id: "T1136", name: "Create Account" },
      { id: "T1543", name: "Create or Modify System Process", subtechniques: [{ id: "T1543.003", name: "Windows Service" }] },
      { id: "T1546", name: "Event Triggered Execution" },
      { id: "T1133", name: "External Remote Services" },
      { id: "T1574", name: "Hijack Execution Flow" },
    ],
  },
  {
    id: "TA0004",
    name: "Privilege Escalation",
    shortName: "privilege-escalation",
    description: "Techniques used to gain higher-level permissions on a system or network.",
    techniques: [
      { id: "T1548", name: "Abuse Elevation Control Mechanism" },
      { id: "T1134", name: "Access Token Manipulation" },
      { id: "T1547", name: "Boot or Logon Autostart Execution" },
      { id: "T1543", name: "Create or Modify System Process" },
      { id: "T1484", name: "Domain Policy Modification" },
      { id: "T1068", name: "Exploitation for Privilege Escalation" },
      { id: "T1055", name: "Process Injection" },
      { id: "T1078", name: "Valid Accounts" },
    ],
  },
  {
    id: "TA0005",
    name: "Defense Evasion",
    shortName: "defense-evasion",
    description: "Techniques used to avoid detection throughout a compromise.",
    techniques: [
      { id: "T1140", name: "Deobfuscate/Decode Files or Information" },
      { id: "T1070", name: "Indicator Removal", subtechniques: [{ id: "T1070.001", name: "Clear Windows Event Logs" }, { id: "T1070.004", name: "File Deletion" }] },
      { id: "T1036", name: "Masquerading" },
      { id: "T1027", name: "Obfuscated Files or Information" },
      { id: "T1055", name: "Process Injection" },
      { id: "T1218", name: "System Binary Proxy Execution" },
      { id: "T1112", name: "Modify Registry" },
      { id: "T1562", name: "Impair Defenses" },
    ],
  },
  {
    id: "TA0006",
    name: "Credential Access",
    shortName: "credential-access",
    description: "Techniques used to steal credentials like account names and passwords.",
    techniques: [
      { id: "T1110", name: "Brute Force", subtechniques: [{ id: "T1110.001", name: "Password Guessing" }, { id: "T1110.003", name: "Password Spraying" }] },
      { id: "T1003", name: "OS Credential Dumping", subtechniques: [{ id: "T1003.001", name: "LSASS Memory" }] },
      { id: "T1555", name: "Credentials from Password Stores" },
      { id: "T1056", name: "Input Capture" },
      { id: "T1557", name: "Adversary-in-the-Middle" },
      { id: "T1552", name: "Unsecured Credentials" },
      { id: "T1558", name: "Steal or Forge Kerberos Tickets" },
    ],
  },
  {
    id: "TA0007",
    name: "Discovery",
    shortName: "discovery",
    description: "Techniques used to gain knowledge about the system and internal network.",
    techniques: [
      { id: "T1087", name: "Account Discovery" },
      { id: "T1083", name: "File and Directory Discovery" },
      { id: "T1046", name: "Network Service Discovery" },
      { id: "T1135", name: "Network Share Discovery" },
      { id: "T1057", name: "Process Discovery" },
      { id: "T1018", name: "Remote System Discovery" },
      { id: "T1082", name: "System Information Discovery" },
      { id: "T1016", name: "System Network Configuration Discovery" },
    ],
  },
  {
    id: "TA0008",
    name: "Lateral Movement",
    shortName: "lateral-movement",
    description: "Techniques used to move through the environment.",
    techniques: [
      { id: "T1210", name: "Exploitation of Remote Services" },
      { id: "T1534", name: "Internal Spearphishing" },
      { id: "T1570", name: "Lateral Tool Transfer" },
      { id: "T1021", name: "Remote Services", subtechniques: [{ id: "T1021.001", name: "Remote Desktop Protocol" }, { id: "T1021.002", name: "SMB/Windows Admin Shares" }] },
      { id: "T1080", name: "Taint Shared Content" },
      { id: "T1550", name: "Use Alternate Authentication Material" },
    ],
  },
  {
    id: "TA0009",
    name: "Collection",
    shortName: "collection",
    description: "Techniques used to gather data of interest to the adversary goal.",
    techniques: [
      { id: "T1560", name: "Archive Collected Data" },
      { id: "T1123", name: "Audio Capture" },
      { id: "T1119", name: "Automated Collection" },
      { id: "T1005", name: "Data from Local System" },
      { id: "T1039", name: "Data from Network Shared Drive" },
      { id: "T1114", name: "Email Collection" },
      { id: "T1113", name: "Screen Capture" },
    ],
  },
  {
    id: "TA0011",
    name: "Command and Control",
    shortName: "command-and-control",
    description: "Techniques used to communicate with systems under adversary control.",
    techniques: [
      { id: "T1071", name: "Application Layer Protocol", subtechniques: [{ id: "T1071.001", name: "Web Protocols" }, { id: "T1071.004", name: "DNS" }] },
      { id: "T1132", name: "Data Encoding" },
      { id: "T1001", name: "Data Obfuscation" },
      { id: "T1568", name: "Dynamic Resolution" },
      { id: "T1573", name: "Encrypted Channel" },
      { id: "T1105", name: "Ingress Tool Transfer" },
      { id: "T1571", name: "Non-Standard Port" },
      { id: "T1572", name: "Protocol Tunneling" },
    ],
  },
  {
    id: "TA0010",
    name: "Exfiltration",
    shortName: "exfiltration",
    description: "Techniques used to steal data from the target network.",
    techniques: [
      { id: "T1020", name: "Automated Exfiltration" },
      { id: "T1030", name: "Data Transfer Size Limits" },
      { id: "T1048", name: "Exfiltration Over Alternative Protocol" },
      { id: "T1041", name: "Exfiltration Over C2 Channel" },
      { id: "T1567", name: "Exfiltration Over Web Service" },
      { id: "T1029", name: "Scheduled Transfer" },
    ],
  },
  {
    id: "TA0040",
    name: "Impact",
    shortName: "impact",
    description: "Techniques used to disrupt availability or compromise integrity.",
    techniques: [
      { id: "T1531", name: "Account Access Removal" },
      { id: "T1485", name: "Data Destruction" },
      { id: "T1486", name: "Data Encrypted for Impact" },
      { id: "T1565", name: "Data Manipulation" },
      { id: "T1491", name: "Defacement" },
      { id: "T1561", name: "Disk Wipe" },
      { id: "T1499", name: "Endpoint Denial of Service" },
      { id: "T1498", name: "Network Denial of Service" },
      { id: "T1496", name: "Resource Hijacking" },
    ],
  },
];
