apiVersion: v1
kind: Pod
metadata:
  name: db-migrate
  namespace: odosian
spec:
  restartPolicy: Never
  containers:
    - name: db-migrate
      image: busybox
      command: ["sleep", "300"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: odosian-data
