apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: {{ .Values.fleet.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.fleet.name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  version: {{ .Values.version }}
  mode: fleet
  fleetServerEnabled: true
  policyID: {{ .Values.fleet.policyID }}
  http:
    service:
      spec:
        type: {{ .Values.fleet.serviceType }}
  kibanaRef:
    name: {{ .Values.kibana.name }}
  elasticsearchRefs:
  - name: {{ .Values.elasticsearch.name }}
  deployment:
    replicas: {{ .Values.fleet.count }}
    podTemplate:
      spec:
        containers:
        - name: agent
          resources:
            requests:
              memory: {{ .Values.fleet.resources.requests.memory }}
              cpu: {{ .Values.fleet.resources.requests.cpu }}
            limits:
              memory: {{ .Values.fleet.resources.limits.memory }}
              cpu: {{ .Values.fleet.resources.limits.cpu }}
